### ISSUE TITLE
Update new darknet_ros

### ISSUE THREAD

**Issue by jerrychen110** [leggedrobotics/darknet_ros#199]
I have already combined new darknet with the ros, fixed some issues. This is my git repository: https://github.com/jerrychen110/darknet_ros

**Comment by Shame-fight** [comment]
Thank you for your work. Which version of darknet you have fixed, can you give the link, I found that the original darknet has not been updated for a long time. There is still a problem, you are interested in trying to compile ABdarknet into a ros package because he The effect is better than this version. Link: https://github.com/AlexeyAB/darknet/
I look forward to hearing from you. . .
@jerrychen110

**Comment by tomlankhorst** [comment]
Thanks for the info.
